## other configuration excluded from example...
exclude_patterns:
 - config/
 - db/
 - dist/
 - features/
 - **/node_modules/
 - script/
 - **/spec/
 - **/test/
 - **/tests/
 - **/vendor/
 - **/*.d.ts
 - **/*/*.spec.ts
